Controllers/OQCController.cs
using FormProject.Database;
using FormProject.Extension;
using FormProject.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime;
using System.Web;
using System.Web.Mvc;

namespace FormProject.Controllers
{
    public class OQCController : Controller
    {
        // GET: OQC
        public ActionResult OQCChart()
        {
            ViewBag.Filter = Constants.OQCChart;


            return View();
        }

        public JsonResult LoadDailyPerformance(string area, string startDate, string endDate, string oqcProcess, string shift)
        {
            try
            {
                using (var db = new ODIEntities())
                {
                    List<ODI> list = new List<ODI>();
                    var start = DateTime.Parse(startDate);
                    var end = DateTime.Parse(endDate);
                    area = area.Trim();
                    var odiRes = new ODIResponsibility();
                    var dailyTotal = odiRes.odi_DailyPerformance(start, end, area, oqcProcess, shift, db);
                    return Json(new
                    {
                        dailyTotal = dailyTotal
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = e.Message.ToString()

                }, JsonRequestBehavior.AllowGet);
            }

        }

        Stopwatch stopwatch = new Stopwatch();
        public JsonResult LoadData(string area, string startDate, string endDate, string oqcProcess)
        {
            try
            {
                using (var db = new ODIEntities())
                {
                    stopwatch.Start();
                    var start = DateTime.Parse(startDate);
                    var end = DateTime.Parse(endDate);
                    area = area.Trim();
                    oqcProcess = oqcProcess.Trim();
                    var listCustomer = new List<string>();
                    if (area == Constants.All || string.IsNullOrEmpty(area))
                    {
                        listCustomer = db.Areas.Where(m => m.Area1 != Constants.All).Select(m => m.Customer).ToList();
                    }
                    else
                    {
                        listCustomer = db.Areas.Where(m => m.Area1 == area).Select(m => m.Customer).ToList();
                    }

                    //day/night
                    var odiRes = new ODIResponsibility();
                    var dayPerformance = odiRes.odi_DayNightPerformance(start, end, area, oqcProcess, Shift.Day, db);
                    var nightPerformance = odiRes.odi_DayNightPerformance(start, end, area, oqcProcess, Shift.Night, db);
                    stopwatch.Stop();
                    Debug.WriteLine("DayNight:" + stopwatch.ElapsedMilliseconds);

                    stopwatch.Start();
                    // daily performance
                    var dailyTotal = odiRes.odi_DailyPerformance(start, end, area, oqcProcess, "", db);
                    stopwatch.Stop();
                    Debug.WriteLine("Daily:" + stopwatch.ElapsedMilliseconds);
                    stopwatch.Start();
                    // Wo by customer
                    var woTotal = odiRes.odi_WOByCustomer(start, end, area, oqcProcess, false, db);
                    var woNG = odiRes.odi_WOByCustomer(start, end, area, oqcProcess, true, db);
                    stopwatch.Stop();
                    Debug.WriteLine("WoByCustomer:" + stopwatch.ElapsedMilliseconds);
                    stopwatch.Start();
                    // fail rate
                    var totalByFail = odiRes.odi_TotalByFail(start, end, area, oqcProcess, db);
                    stopwatch.Stop();
                    Debug.WriteLine("Fail rate:" + stopwatch.ElapsedMilliseconds);
                    stopwatch.Start();

                    // weekly
                    int diff = (7 + (start.DayOfWeek - DayOfWeek.Monday)) % 7;
                    var weekStartDate = start.AddDays(-1 * diff).Date;
                    var weekEndDate = DateTime.MinValue;
                    var listWeek = new List<WeeklyReview>();
                    var listByDay = odiRes.odi_WeeklyReview(start, end, area, oqcProcess, db);
                    while (weekEndDate < end)
                    {
                        weekEndDate = weekStartDate.AddDays(6);
                        var shownStartDate = weekStartDate < start ? start : weekStartDate;
                        var shownEndDate = weekEndDate > end ? end : weekEndDate;
                        Stopwatch watch = new Stopwatch();
                        watch.Start();
                        listWeek.Add(new WeeklyReview()
                        {
                            date = shownStartDate.ToShortDateString() + "-" + shownEndDate.ToShortDateString(),
                            listByCus = (from p in listByDay
                                         where p.DateOccur >= shownStartDate && p.DateOccur <= shownEndDate
                                         group p by p.Customer into g
                                         select new ChartItem
                                         {
                                             Customer = g.Key,
                                             TotalCheck = g.Sum(m => m.TotalCheck),
                                             TotalNG = g.Sum(m => m.TotalNG)
                                         }).ToList()
                        });
                        watch.Stop();
                        Debug.WriteLine("Each Week:" + watch.ElapsedMilliseconds);
                        weekStartDate = weekStartDate.AddDays(7);
                    }
                    stopwatch.Stop();
                    Debug.WriteLine("Weekly:" + stopwatch.ElapsedMilliseconds);

                    stopwatch.Start();
                    // man-power
                    var listByArea = odiRes.odi_ManPower(start, end, area, oqcProcess, db);
                    stopwatch.Stop();
                    Debug.WriteLine("ManPower:" + stopwatch.ElapsedMilliseconds);
                    return Json(new
                    {
                        dayPerformance = dayPerformance,
                        nightPerformance = nightPerformance,
                        dailyTotal = dailyTotal,
                        totalByFail = totalByFail,
                        listWeek = listWeek,
                        listByArea = listByArea,
                        listCustomer = listCustomer,
                        woTotal = woTotal,
                        woNG = woNG

                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { status = "ERORR" }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult LoaDataMTDQuantity(string startDate, string endDate, string filter, string value, string chart_view, string station)
        {
            try
            {
                using (var db = new ODIEntities())
                {
                    Stopwatch stopwatch = new Stopwatch();
                    stopwatch.Start();
                    if (string.IsNullOrEmpty(chart_view))
                        chart_view = Option.DAY;
                    chart_view = chart_view.Trim();
                    var start = DateTime.Parse(startDate);
                    var end = DateTime.Parse(endDate);
                    float targetPPM = 9; // mặc định

                    if (filter == "Area")
                    {
                        if (value == "AUTO") targetPPM = PPM.AUTO;
                        else
                        {
                            // nếu khoảng thời gian trong 1 tháng
                            if(start.Month == end.Month)
                            {
                                targetPPM= PPM.ALL[start.Month-1];
                            }
                            else
                            {
                                targetPPM = 9;
                            }
                        }
                        if (start.Year == 2024)
                        {
                            if (start.Month == 1 || start.Month == 2 || start.Month == 3)
                            {
                                targetPPM = 25;
                            }
                        }
                    }
                   
                    var odiRes = new ODIResponsibility();
                    if (value == "ALL") value = "";
                    var defectionList = odiRes.odi_Defection(start, end, station, filter, value, db);
                    var oneDay = TimeSpan.FromDays(1);
                    var listDefectionByDate = new List<DefectionByDate>();
                    var jpDefection = db.TypeNGs.ToList();
                    int maxNGTotal = 0;
                    int maxNG = 0;
                    foreach (var def in jpDefection)
                    {
                        var defByDate = new DefectionByDate();
                        defByDate.defection = def.TypeNG1;
                        defByDate.jpDefection = def.JP;
                        var listTotal = defectionList.Where(m => m.Defection.Trim() == def.TypeNG1.Trim()).ToList();
                        var listByDate = new List<IncrementalTimeLine>();
                        var totalNGInDef = defectionList.Where(m => m.Defection.Trim() == def.TypeNG1.Trim()).Sum(m => m.TotalNG);
                        if (totalNGInDef > maxNGTotal)
                            maxNGTotal = totalNGInDef;
                        var currentStartDayInTable = start;
                        var currentEndDayInTable = start;
                        if (chart_view == Option.WEEK)
                        {

Views/Shared/_Layout.cshtml
@using FormProject.Database
@using FormProject.Controllers.Helper
@{
    /**/

    User user = (User)HttpContext.Current.Session["User"];
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UMC Việt Nam</title>
    <link rel="icon" href="@Url.Content("~/favicon.ico")" type="image/x-icon" />
    <link href="~/Content/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />

    @*<link href="~/Content/css/common.css" rel="stylesheet" />*@
    <link href="@Url.ContentVersioned("~/Content/css/common","css")" rel="stylesheet" />

</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->

        <ul style ="background-color:dodgerblue"class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="nav-link" href="#">
                <img style="padding:5px 10px 10px 15px;" class="img-profile" src="~/Resources/logo.png">
                @if (HttpContext.Current.Session["User"] != null)
                {
                    <span class="mr-2 d-none d-lg-inline text-white small ml-3">@(FormProject.Resource.Hello + " " + user.Name)</span>
                }

            </a>


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div style="color: wheat; font-size: 12px" class="sidebar-heading colo">
                Cài đặt tài khoản
            </div>

            <!-- Nav Item - Pages Collapse Menu -->

            @if (user != null)
            {

                <li class="nav-item">
                    <a class="nav-link collapsed" href="@Url.Action("Logout", "Home")">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>@FormProject.Resource.Logout</span>
                    </a>

                </li>
                if (user.Role != null && user.Role.Name == Constants.Role_Admin)
                {


                    <li class="nav-item">
                        <a class="nav-link collapsed" href="@Url.Action("Register", "Home")">
                            <i class="fas fa-fw fa-user-plus"></i>
                            <span>@FormProject.Resource.CreateNewUser</span>
                        </a>
                    </li>

                }

                <hr class="sidebar-divider">

                <div class="sidebar-heading">
                    Thông tin Claim
                </div>


                <div class="list-filter-claim">
                    <li class="nav-item" name="@Constants.All">
                        <a class="nav-link" href="@Url.Action("Index", "Claim",new { filter = Constants.All})">
                            <i class="fas fa-fw fa-home"></i>
                            <span>Tất cả</span>
                        </a>
                    </li>

                    <li class="nav-item" name="@Constants.Filter_Draft">
                        <a class="nav-link collapsed" href="@Url.Action("Index", "Claim",new { filter = Constants.Filter_Draft})">
                            <i class="fas fa-fw fa-folder"></i>
                            <span>@FormProject.Resource.Draft</span>
                        </a>
                    </li>

                    <li class="nav-item" name="@Constants.Filter_WaitingMe">
                        <a class="nav-link" href="@Url.Action("Index", "Claim",new { filter = Constants.Filter_WaitingMe})">
                            <i class="fas fa-bell fa-fw"></i>
                            <span>
                                @FormProject.Resource.WattingMe
                            </span>
                            @{
                                if (HttpContext.Current.Application["NumberWaitMe"] != null)
                                {
                                    var numberWait = (int)HttpContext.Current.Application["NumberWaitMe"];
                                    if (numberWait > 0)
                                    {
                                        <span class="badge badge-danger badge-counter" style="font-size:10px">@(numberWait + "+")</span>
                                    }
                                }
                            }


                        </a>
                    </li>

                    <li class="nav-item" name="@Constants.Filter_MyClaim">
                        <a class="nav-link" href="@Url.Action("Index", "Claim",new { filter = Constants.Filter_MyClaim})">
                            <i class="fas fa-fw fa-table"></i>
                            <span>@FormProject.Resource.MyClaim</span>
                        </a>
                    </li>
                    <li class="nav-item" name="@Constants.Claim_Chart">
                        <a class="nav-link" href="@Url.Action("Chart", "Claim")">
                            <i class="fas fa-chart-bar"></i>
                            <span>@FormProject.Resource.Chart</span>
                        </a>
                    </li>
                </div>
                <!-- Nav Item - Dashboard -->


            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" href="@Url.Action("Login", "Home")">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>@FormProject.Resource.Login</span>
                    </a>

                </li>

            }
            <input type="hidden" value="@ViewBag.Filter" id="filter" />
            <hr class="sidebar-divider d-none d-md-block">
            <div style="color:wheat; font-size:12px" class="sidebar-heading">
                Thông tin OQC
            </div>
            <li class="nav-item" name="@Constants.OQCChart">
                <a class="nav-link" href="@Url.Action("OQCChart", "OQC")">
                    <i class="fas  fa-chart-bar"></i>

                    <span>Biểu đồ Dyanmic data</span>
                </a>


            </li>
            <li class="nav-item" name="@Constants.OQCChartAreaOverview">
                <a class="nav-link" href="@Url.Action("OQCChartAreaOverview", "OQC")">
                    <i class="fas  fa-chart-bar"></i>

                    <span>Biểu đồ Area Overview</span>
                </a>


            </li>
            <li class="nav-item" name="@Constants.MTDQuantity">
                <a class="nav-link" href="@Url.Action("MTDQuantity", "OQC")">
                    <i class="fas  fa-chart-bar"></i>

                    <span>Biểu đồ MTD Quantity</span>
                </a>


            </li>
            <li class="nav-item" name="@Constants.OQCChartDefection">
                <a class="nav-link" href="@Url.Action("OQCChartDefection", "OQC")">
                    <i class="fas  fa-chart-bar"></i>

                    <span>Biểu đồ Defection</span>
                </a>
            </li>
            <li class="nav-item" name="@Constants.OQCChartPerformance">
                <a class="nav-link" href="@Url.Action("OQCChartPerformance", "OQC")">
                    <i class="fas  fa-chart-bar"></i>

                    <span>Biểu đồ Performance</span>
                </a>


            </li>
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>

        <!-- End of Sidebar -->

        @RenderBody()
    </div>

    <!-- Footer -->
    <!-- End of Footer -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/ckfinder/ckfinder.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="@Url.ContentVersioned("~/Scripts/custom/common","js")"></script>
    <script src="@Url.ContentVersioned("~/Scripts/custom/claim_view","js")"></script>
    <script src="@Url.ContentVersioned("~/Scripts/custom/chart_common","js")"></script>
    
    @RenderSection("scripts", required: false)
</body>
</html>