Controllers/ProcessController.cs
using FormProject.Controllers.Database;
using FormProject.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormProject.Controllers
{
    public class ProcessController : Controller
    {
        ProcessDbManager processManager = new ProcessDbManager();

        public ActionResult CreateProcess()
        {
            List<Process> list = processManager.OrderByDescending();
            return View(list);
        }

        [HttpPost]
        public ActionResult CreateProcess(string name, string canEdit)
        {
            if (processManager.GetProcessByName(name) != null)
            {
                ModelState.AddModelError("Error", "Process đã có tên này rồi!");
                List<Process> listOld = processManager.OrderByDescending();
                return View(listOld);
            }
            Process process = new Process() { Name = name, CanEdit = canEdit == null ? 0 : 1 };

            if (processManager.Add(process) == Constants.STATUS_ERROR)
            {
                ModelState.AddModelError("Error", Resource.Error_Common);
                List<Process> listOld = processManager.OrderByDescending();
                return View(listOld);
            }
            List<Process> list = processManager.OrderByDescending();
            return View(list);
        }

        public ActionResult DeleteProcess(int Id)
        {
            if (processManager.Delete(Id) == Constants.STATUS_ERROR)
            {
                ModelState.AddModelError("Error", Resource.Error_Common);
                return View();
            }
            return RedirectToAction("CreateProcess");
        }

        public ActionResult CreateProcessTemplate()
        {
            ViewBag.ProcessList = processManager.GetAllProcess();
            return View();
        }

        public ActionResult SaveProcess(string displayName, string process)
        {
            ProcessList pList = new ProcessList()
            {
                DisplayName = displayName,
                Process = process
            };
            if (processManager.Add(pList) == Constants.STATUS_ERROR)
            {
                ModelState.AddModelError("Error", Resource.Error_Common);
                return View();
            }
            TempData["SaveProcess"] = Constants.Result_OK;
            TempData["SaveProcessContent"] = "Bạn vừa tạo thành công 1 process";
            return RedirectToAction("CreateProcessTemplate");
        }
    }
}

Views/Process/CreateProcess.cshtml
@using FormProject.Database;
@{
    ViewBag.Title = "CreateProcess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Process>
<div class="container shadow mt-5">

    <!-- Claim list -->
    <div class="card-body mt-10">
        <form action="CreateProcess" method="post">
            @Html.ValidationMessage("Error", new { @class = "text-danger", id = "error" })
            <input type="text" class="form-control" placeholder="Nhập tên process" name="name" required />
            <label class="checkbox-inline mt-3"><input type="checkbox" value="1" name="canEdit"> Có thể sửa</label>
            <br />
            <input type="submit" class="btn btn-primary" value="Thêm" />
        </form>
        <br />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Tên process</th>
                    <th scope="col">Có thể edit</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var process in Model)
                    {
                        <tr>
                            <td>@process.Name</td>
                            <td>@(process.CanEdit == 1 ? "Có" : "Không")</td>
                            @*<td scope="col">
                                <div class="btn btn-danger">
                                    <a class="text-white text-decoration-none" href="@Url.Action("DeleteProcess","Process", new { Id = process.Id })">Xóa</a>
                                </div>
                            </td>*@
                        </tr>
                    }
                }

            </tbody>
        </table>

    </div>
</div>

Views/Process/CreateProcessTemplate.cshtml
@{
    ViewBag.Title = "CreateProcessTemplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using FormProject.Database;
<div class="container shadow mt-5">

    <!-- Claim list -->
    <div class="card-body mt-10">
        @if (TempData["SaveProcess"] != null && TempData["SaveProcess"].ToString() == Constants.Result_OK)
        {
            <div class="alert alert-success m-3" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @TempData["SaveProcessContent"]
            </div>
        }
        @if (ViewBag.ProcessList != null)
        {
            <form action="SaveProcess" method="post" id="save-form">
                @Html.ValidationMessage("Error", new { @class = "text-danger", id = "error" })
                <input type="text" class="form-control" placeholder="Tên process" name="displayName" required />
                <select class="form-control mt-3" required>
                    <option value="">Chọn Process</option>
                    @foreach (Process process in ViewBag.ProcessList)
                    {
                        <option value="@process.Id">@process.Name</option>
                    }
                </select>
                <input type="button" class="btn btn-primary mt-3" value="Thêm" onclick="return addStep()" />
                <input type="button" class="btn btn-danger mt-3" value="Xóa Step" onclick="return deleteStep()" />
                <br /><br />
                <div id="steps-form" class="steps-form">
                    <div class="steps-row setup-panel">
                    </div>
                </div>
                <input type="hidden" value="" name="process" id="process" />
                <input type="button" class="btn btn-primary mt-3" value="Lưu" onclick="return save()" />
            </form>

        }

    </div>
</div>
@section scripts{
    <script src="~/Scripts/custom/process.js"></script>
}